### ISSUE TITLE
图标我自己改造了一下，可以了。但是能不能再增加一个主题功能啊

### ISSUE THREAD

**Issue by liujianchao1995** [buuing/vue-right-menu#2]
就是在页面的不同部位，出现的右键菜单是不同样式的，比如内容区就是亮色，顶栏区就是暗色。

**Comment by liujianchao1995** [comment]
喔，我又改造了一下，可以更换主题了。

**Comment by buuing** [comment]
> 喔，我又改造了一下，可以更换主题了。

hhh, 刚看到, 当时样式没有过多的维护, 就是担心别人的后台主题不搭配
